
import __ASTRO_IMAGE_IMPORT_Z1REoRY from "@assets/profile/avatar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fabout%2F-index.md";
import __ASTRO_IMAGE_IMPORT_Z11Coq1 from "@assets/profile/avatar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fjohn-doe.md";
import __ASTRO_IMAGE_IMPORT_1ka8xu from "@assets/profile/avatar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fjane-doe.md";
import __ASTRO_IMAGE_IMPORT_Z11JCye from "@assets/poetry/phantom-of-this-frozen-place.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpoetry%2Fphantom-of-this-frozen-place.md";
import __ASTRO_IMAGE_IMPORT_wOFyI from "@assets/recipes/banana-bread.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fbanana-bread.md";
import __ASTRO_IMAGE_IMPORT_ZXDyHR from "@assets/astro-star4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2F-index.md";
import __ASTRO_IMAGE_IMPORT_7NMnW from "@assets/recipes/margherita-pizza.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fmargherita-pizza.md";
import __ASTRO_IMAGE_IMPORT_Z1CRu7q from "@assets/recipes/herb-chicken.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fherb-chicken.md";
import __ASTRO_IMAGE_IMPORT_1WBDSQ from "@assets/recipes/mushroom-risotto.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fmushroom-risotto.md";
import __ASTRO_IMAGE_IMPORT_Z22UQRC from "@assets/recipes/sweet-potato-chili.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fsweet-potato-chili.md";
import __ASTRO_IMAGE_IMPORT_Z1LejC8 from "@assets/recipes/veggie-stir-fry.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fveggie-stir-fry.md";
import __ASTRO_IMAGE_IMPORT_2hwOvD from "@assets/recipes/spaghetti-carbonara.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fspaghetti-carbonara.md";
export default new Map([["@assets/profile/avatar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fabout%2F-index.md", __ASTRO_IMAGE_IMPORT_Z1REoRY], ["@assets/profile/avatar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fjohn-doe.md", __ASTRO_IMAGE_IMPORT_Z11Coq1], ["@assets/profile/avatar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fjane-doe.md", __ASTRO_IMAGE_IMPORT_1ka8xu], ["@assets/poetry/phantom-of-this-frozen-place.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpoetry%2Fphantom-of-this-frozen-place.md", __ASTRO_IMAGE_IMPORT_Z11JCye], ["@assets/recipes/banana-bread.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fbanana-bread.md", __ASTRO_IMAGE_IMPORT_wOFyI], ["@assets/astro-star4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2F-index.md", __ASTRO_IMAGE_IMPORT_ZXDyHR], ["@assets/recipes/margherita-pizza.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fmargherita-pizza.md", __ASTRO_IMAGE_IMPORT_7NMnW], ["@assets/recipes/herb-chicken.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fherb-chicken.md", __ASTRO_IMAGE_IMPORT_Z1CRu7q], ["@assets/recipes/mushroom-risotto.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fmushroom-risotto.md", __ASTRO_IMAGE_IMPORT_1WBDSQ], ["@assets/recipes/sweet-potato-chili.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fsweet-potato-chili.md", __ASTRO_IMAGE_IMPORT_Z22UQRC], ["@assets/recipes/veggie-stir-fry.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fveggie-stir-fry.md", __ASTRO_IMAGE_IMPORT_Z1LejC8], ["@assets/recipes/spaghetti-carbonara.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fspaghetti-carbonara.md", __ASTRO_IMAGE_IMPORT_2hwOvD]]);
		